/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Banka.java
 *
 * Created on May 3, 2013, 9:21:46 AM
 */
package fri.kcr;

import java.awt.event.KeyEvent;
import java.io.FileWriter;
import java.io.PrintWriter;

/**
 *
 * @author Adrian Jarc
 */

public class Banka extends javax.swing.JFrame {
    
    private static Oseba[] osebe = new Oseba[2];
    private String operacije;

    /** Creates new form Banka */
    public Banka() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Prijavnik = new javax.swing.JFrame();
        ime = new javax.swing.JTextField();
        geslo = new javax.swing.JPasswordField();
        potrditev = new javax.swing.JButton();
        l_ime = new javax.swing.JLabel();
        l_geslo = new javax.swing.JLabel();
        n_ime = new javax.swing.JLabel();
        n_geslo = new javax.swing.JLabel();
        Obvestilnik = new javax.swing.JFrame();
        obvestilnik1 = new javax.swing.JLabel();
        obvestilnik2 = new javax.swing.JLabel();
        obvestilnik_vredu = new javax.swing.JButton();
        Operacije = new javax.swing.JFrame();
        Izpisi_operacije = new javax.swing.JScrollPane();
        izpis_operacij = new javax.swing.JTextArea();
        Storitve = new javax.swing.JTabbedPane();
        UPN = new javax.swing.JPanel();
        l_znesek = new javax.swing.JLabel();
        v_znesek = new javax.swing.JTextField();
        n_znesek = new javax.swing.JLabel();
        l_EUR = new javax.swing.JLabel();
        l_IBAN = new javax.swing.JLabel();
        v_IBAN = new javax.swing.JTextField();
        n_IBAN = new javax.swing.JLabel();
        l_SI56 = new javax.swing.JLabel();
        l_referenca = new javax.swing.JLabel();
        v_referenca = new javax.swing.JTextField();
        n_referenca = new javax.swing.JLabel();
        l_SI = new javax.swing.JLabel();
        v_SI = new javax.swing.JTextField();
        l_naziv = new javax.swing.JLabel();
        v_naziv = new javax.swing.JTextField();
        l_ulica = new javax.swing.JLabel();
        v_ulica = new javax.swing.JTextField();
        l_posta = new javax.swing.JLabel();
        v_posta = new javax.swing.JTextField();
        l_postnast = new javax.swing.JLabel();
        v_postnast = new javax.swing.JTextField();
        vredu = new javax.swing.JButton();
        n_posta = new javax.swing.JLabel();
        l_osebnizaz = new javax.swing.JLabel();
        v_osebnizaz = new javax.swing.JTextField();
        Nakazilo = new javax.swing.JPanel();
        l_strac = new javax.swing.JLabel();
        v_strac = new javax.swing.JTextField();
        n_strac = new javax.swing.JLabel();
        l_imeprej = new javax.swing.JLabel();
        v_imeprej = new javax.swing.JTextField();
        l_hitroplac = new javax.swing.JLabel();
        v_hitroplac = new javax.swing.JTextField();
        ip_vredu = new javax.swing.JButton();
        l_ip_znesek = new javax.swing.JLabel();
        v_ip_znesek = new javax.swing.JTextField();
        n_ip_znesek = new javax.swing.JLabel();
        l_ip_EUR = new javax.swing.JLabel();
        Stanje = new javax.swing.JPanel();
        prikaz_stanja = new javax.swing.JScrollPane();
        stanja = new javax.swing.JTextArea();
        Meni = new javax.swing.JMenuBar();
        Datoteka = new javax.swing.JMenu();
        m_izhod = new javax.swing.JMenuItem();
        Pomoc = new javax.swing.JMenu();
        m_avtor = new javax.swing.JMenuItem();

        Prijavnik.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Prijavnik.setTitle("Prijava");
        Prijavnik.setMinimumSize(new java.awt.Dimension(400, 300));
        Prijavnik.setResizable(false);
        Prijavnik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                p_prijavi(evt);
            }
        });

        ime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                preveri(evt);
            }
        });
        ime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                p_prijavi(evt);
            }
        });

        geslo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                preveri(evt);
            }
        });
        geslo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                p_prijavi(evt);
            }
        });

        potrditev.setText("Potrdi");
        potrditev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prijavi(evt);
            }
        });
        potrditev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                p_prijavi(evt);
            }
        });

        l_ime.setText("Ime:");

        l_geslo.setText("Geslo:");

        javax.swing.GroupLayout PrijavnikLayout = new javax.swing.GroupLayout(Prijavnik.getContentPane());
        Prijavnik.getContentPane().setLayout(PrijavnikLayout);
        PrijavnikLayout.setHorizontalGroup(
            PrijavnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrijavnikLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PrijavnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l_geslo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_ime, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrijavnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ime, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(geslo))
                .addGap(12, 12, 12)
                .addGroup(PrijavnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n_geslo, 0, 1, Short.MAX_VALUE)
                    .addComponent(n_ime, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(PrijavnikLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(potrditev)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        PrijavnikLayout.setVerticalGroup(
            PrijavnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrijavnikLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(PrijavnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n_ime, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_ime))
                .addGap(36, 36, 36)
                .addGroup(PrijavnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n_geslo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_geslo))
                .addGap(58, 58, 58)
                .addComponent(potrditev)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        Obvestilnik.setTitle("Obvestilo");
        Obvestilnik.setMinimumSize(new java.awt.Dimension(400, 300));
        Obvestilnik.setResizable(false);

        obvestilnik_vredu.setText("Vredu");
        obvestilnik_vredu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapri(evt);
            }
        });

        javax.swing.GroupLayout ObvestilnikLayout = new javax.swing.GroupLayout(Obvestilnik.getContentPane());
        Obvestilnik.getContentPane().setLayout(ObvestilnikLayout);
        ObvestilnikLayout.setHorizontalGroup(
            ObvestilnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ObvestilnikLayout.createSequentialGroup()
                .addGroup(ObvestilnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ObvestilnikLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ObvestilnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(obvestilnik2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(obvestilnik1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)))
                    .addGroup(ObvestilnikLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(obvestilnik_vredu)))
                .addContainerGap())
        );
        ObvestilnikLayout.setVerticalGroup(
            ObvestilnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ObvestilnikLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(obvestilnik1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(obvestilnik2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(obvestilnik_vredu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Operacije.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Operacije.setTitle("Izvedene operacije");
        Operacije.setMinimumSize(new java.awt.Dimension(400, 300));
        Operacije.setResizable(false);

        izpis_operacij.setEditable(false);
        izpis_operacij.setColumns(20);
        izpis_operacij.setRows(5);
        izpis_operacij.setMinimumSize(new java.awt.Dimension(400, 300));
        Izpisi_operacije.setViewportView(izpis_operacij);

        Operacije.getContentPane().add(Izpisi_operacije, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Banka Šparovček");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                Operacije(evt);
            }
        });

        Storitve.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prijava(evt);
            }
        });

        l_znesek.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l_znesek.setLabelFor(v_znesek);
        l_znesek.setText("Znesek");

        v_znesek.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                UPNnapake(evt);
            }
        });

        n_znesek.setLabelFor(v_znesek);

        l_EUR.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        l_EUR.setLabelFor(v_znesek);
        l_EUR.setText("EUR");

        l_IBAN.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l_IBAN.setLabelFor(v_IBAN);
        l_IBAN.setText("IBAN");

        v_IBAN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                UPNnapake(evt);
            }
        });

        n_IBAN.setLabelFor(v_IBAN);

        l_SI56.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        l_SI56.setLabelFor(v_IBAN);
        l_SI56.setText("SI-56");

        l_referenca.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l_referenca.setLabelFor(v_referenca);
        l_referenca.setText("Referenca");

        v_referenca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                UPNnapake(evt);
            }
        });

        n_referenca.setLabelFor(v_referenca);

        l_SI.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        l_SI.setLabelFor(v_SI);
        l_SI.setText("SI");

        l_naziv.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l_naziv.setLabelFor(v_naziv);
        l_naziv.setText("Naziv");

        l_ulica.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l_ulica.setLabelFor(v_ulica);
        l_ulica.setText("Ulica");

        l_posta.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l_posta.setLabelFor(v_posta);
        l_posta.setText("Pošta");

        l_postnast.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l_postnast.setLabelFor(v_postnast);
        l_postnast.setText("Poštna št.");

        vredu.setText("Vredu");
        vredu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                narediUPN(evt);
            }
        });

        l_osebnizaz.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l_osebnizaz.setLabelFor(v_osebnizaz);
        l_osebnizaz.setText("Osebni zaznamek: ");

        javax.swing.GroupLayout UPNLayout = new javax.swing.GroupLayout(UPN);
        UPN.setLayout(UPNLayout);
        UPNLayout.setHorizontalGroup(
            UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UPNLayout.createSequentialGroup()
                .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UPNLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UPNLayout.createSequentialGroup()
                                .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(l_EUR)
                                        .addComponent(l_SI56))
                                    .addGroup(UPNLayout.createSequentialGroup()
                                        .addComponent(l_SI)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(v_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l_referenca)
                                    .addComponent(l_IBAN)
                                    .addComponent(l_znesek)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UPNLayout.createSequentialGroup()
                                        .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(v_znesek, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                            .addComponent(v_IBAN, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                            .addComponent(v_referenca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(n_referenca, 0, 1, Short.MAX_VALUE)
                                            .addComponent(n_IBAN, 0, 1, Short.MAX_VALUE)
                                            .addComponent(n_znesek, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)))))
                            .addGroup(UPNLayout.createSequentialGroup()
                                .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(v_ulica, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_ulica))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(v_posta, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_posta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(v_postnast)
                                    .addComponent(l_postnast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))))
                    .addGroup(UPNLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(vredu)))
                .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UPNLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n_posta, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UPNLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(v_osebnizaz, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_osebnizaz))))
                .addGap(47, 47, 47))
            .addGroup(UPNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UPNLayout.createSequentialGroup()
                        .addComponent(v_naziv)
                        .addGap(282, 282, 282))
                    .addGroup(UPNLayout.createSequentialGroup()
                        .addComponent(l_naziv)
                        .addContainerGap(584, Short.MAX_VALUE))))
        );
        UPNLayout.setVerticalGroup(
            UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UPNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_znesek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n_znesek, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(v_znesek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l_EUR)))
                .addGap(30, 30, 30)
                .addComponent(l_IBAN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_IBAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_SI56)
                    .addComponent(n_IBAN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_referenca)
                    .addComponent(l_osebnizaz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UPNLayout.createSequentialGroup()
                        .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n_referenca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_SI)
                            .addComponent(v_SI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v_referenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(l_naziv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v_naziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_ulica)
                            .addComponent(l_posta)
                            .addComponent(l_postnast, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UPNLayout.createSequentialGroup()
                                .addComponent(n_posta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(UPNLayout.createSequentialGroup()
                                .addGroup(UPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(v_ulica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(v_posta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(v_postnast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(vredu))))
                    .addGroup(UPNLayout.createSequentialGroup()
                        .addComponent(v_osebnizaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))))
        );

        Storitve.addTab("UPN", UPN);

        l_strac.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l_strac.setLabelFor(v_strac);
        l_strac.setText("Številka računa:");

        v_strac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IstaPosNapake(evt);
            }
        });

        n_strac.setLabelFor(v_strac);

        l_imeprej.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l_imeprej.setLabelFor(v_imeprej);
        l_imeprej.setText("Ime prejemnika: ");

        v_imeprej.setEditable(false);

        l_hitroplac.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l_hitroplac.setLabelFor(v_hitroplac);
        l_hitroplac.setText("Hitro plačilo: ");

        ip_vredu.setText("Vredu");
        ip_vredu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NarediIstaPos(evt);
            }
        });

        l_ip_znesek.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l_ip_znesek.setLabelFor(v_ip_znesek);
        l_ip_znesek.setText("Znesek: ");

        v_ip_znesek.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IstaPosNapake(evt);
            }
        });

        n_ip_znesek.setLabelFor(v_ip_znesek);

        l_ip_EUR.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        l_ip_EUR.setLabelFor(v_ip_znesek);
        l_ip_EUR.setText("EUR");

        javax.swing.GroupLayout NakaziloLayout = new javax.swing.GroupLayout(Nakazilo);
        Nakazilo.setLayout(NakaziloLayout);
        NakaziloLayout.setHorizontalGroup(
            NakaziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NakaziloLayout.createSequentialGroup()
                .addGroup(NakaziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NakaziloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(NakaziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_strac)
                            .addComponent(l_imeprej)
                            .addGroup(NakaziloLayout.createSequentialGroup()
                                .addGroup(NakaziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NakaziloLayout.createSequentialGroup()
                                        .addComponent(l_ip_EUR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(v_ip_znesek, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(v_imeprej, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(v_strac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(NakaziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(n_ip_znesek, 0, 1, Short.MAX_VALUE)
                                    .addComponent(n_strac, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)))))
                    .addGroup(NakaziloLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(ip_vredu))
                    .addGroup(NakaziloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(l_hitroplac))
                    .addGroup(NakaziloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(l_ip_znesek))
                    .addGroup(NakaziloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(v_hitroplac, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        NakaziloLayout.setVerticalGroup(
            NakaziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NakaziloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_strac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NakaziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n_strac, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v_strac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(l_imeprej)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v_imeprej, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l_ip_znesek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NakaziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_ip_znesek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n_ip_znesek, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_ip_EUR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(l_hitroplac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v_hitroplac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(ip_vredu)
                .addContainerGap())
        );

        Storitve.addTab("Nakazilo pri isti poslovalnici", Nakazilo);

        Stanje.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                izpisiStanje(evt);
            }
        });
        Stanje.setLayout(new java.awt.BorderLayout());

        prikaz_stanja.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                izpisiStanje(evt);
            }
        });

        stanja.setEditable(false);
        stanja.setColumns(20);
        stanja.setRows(5);
        stanja.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                izpisiStanje(evt);
            }
        });
        prikaz_stanja.setViewportView(stanja);

        Stanje.add(prikaz_stanja, java.awt.BorderLayout.CENTER);

        Storitve.addTab("Pregled stanja", Stanje);

        getContentPane().add(Storitve, java.awt.BorderLayout.PAGE_START);

        Datoteka.setText("Datoteka");

        m_izhod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        m_izhod.setMnemonic('I');
        m_izhod.setText("Izhod");
        m_izhod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodaMeni(evt);
            }
        });
        Datoteka.add(m_izhod);

        Meni.add(Datoteka);

        Pomoc.setText("Pomoč");

        m_avtor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        m_avtor.setMnemonic('A');
        m_avtor.setText("O Avtorju");
        m_avtor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodaMeni(evt);
            }
        });
        Pomoc.add(m_avtor);

        Meni.add(Pomoc);

        setJMenuBar(Meni);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prijava(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prijava
        if(!preveriPrijavo("prijava")){
            this.setVisible(false);
            Prijavnik.setVisible(true);
        }
    }//GEN-LAST:event_prijava

    private void preveri(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_preveri
        if(evt.getSource() == ime){
            if(!ime.getText().equalsIgnoreCase(osebe[0].dobiIme())){
                n_ime.setText("!");
            } else {
                n_ime.setText("");
            }
        } else if(evt.getSource() == geslo){
            if(!geslo.getText().equals(osebe[0].dobiGeslo())){
                n_geslo.setText("!");
            } else {
                n_geslo.setText("");
            }
        }
    }//GEN-LAST:event_preveri

    private void prijavi(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prijavi
        if(preveriPrijavo("prijavi")){
            Prijavnik.setVisible(false);
            this.setVisible(true);
        } else {
            obvestilnik1.setText("V nekaterih poljih ni pravilnega vnosa.");
            obvestilnik2.setText("Poištite polja označena z !.");
            Obvestilnik.setVisible(true);
        }
    }//GEN-LAST:event_prijavi

    private void zapri(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapri
        Obvestilnik.setVisible(false);
    }//GEN-LAST:event_zapri

    private void p_prijavi(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_prijavi
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(preveriPrijavo("prijavi")){
            Prijavnik.setVisible(false);
            this.setVisible(true);
        } else {
            obvestilnik1.setText("V nekaterih poljih ni pravilnega vnosa.");
            obvestilnik2.setText("Poištite polja označena z !.");
            Obvestilnik.setVisible(true);
        }
        }
    }//GEN-LAST:event_p_prijavi

    private void narediUPN(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_narediUPN
        if(UPNpreveriVse()){
            try {
                PrintWriter out = new PrintWriter(new FileWriter("upn"));
                out.println("Podatki o prejemniku:");
                out.println("Naziv: " + v_naziv.getText());
                out.println("Naslov:");
                out.println(v_ulica.getText());
                out.println(v_postnast.getText() + " " +  v_posta.getText());
                out.println("Številka računa: SI56 " + v_IBAN.getText());
                out.println("Referenca: SI" + v_SI.getText() + " " + v_referenca.getText());           
                out.println("Znesek:");                
                out.println(v_znesek.getText() + " EUR");
                out.println("Zaznamek: " + v_osebnizaz.getText());
                out.println("________________________________________________");
                out.println("Podatki o plačniku:");
                out.println("Ime: " + osebe[0].dobiIme());
                out.println("Številka računa: " + osebe[0].vrniRacune()[1].vrniStevilko());
                out.close();
                Obvestilnik.setVisible(true);
                obvestilnik1.setText("Datoteka z imenom upn.");
                obvestilnik2.setText("Je bila uspešno shranjena.");
            } catch (Exception e) {
                System.err.print(e);
                Obvestilnik.setVisible(true);
                obvestilnik1.setText("Napaka pri pisanju datoteke.");
                obvestilnik2.setText("");
            }
            double d = Double.parseDouble(v_znesek.getText());
            osebe[0].vrniRacune()[1].spremeniStanje(d);
            if(operacije == null){
                operacije = ("UPN (»" + v_osebnizaz.getText() + "«)\n");
            } else{
                operacije += ("UPN (»" + v_osebnizaz.getText() + "«)\n");
            }
        } else{
            obvestilnik1.setText("V nekaterih poljih ni pravilnega vnosa.");
            obvestilnik2.setText("Poištite polja označena z !.");
            Obvestilnik.setVisible(true);
        }
    }//GEN-LAST:event_narediUPN

    private void UPNnapake(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UPNnapake
        if(evt.getSource() == v_znesek){
            try{
                double d = Double.parseDouble(v_znesek.getText());
                n_znesek.setText("");
            } catch (Exception e){
                n_znesek.setText("!");
            }
        } else if(evt.getSource() == v_IBAN){
            try{
                long d = Long.parseLong(v_IBAN.getText());
                n_IBAN.setText("");
            } catch (Exception e){
                n_IBAN.setText("!");
            }
        } else if(evt.getSource() == v_referenca){
            if(!v_SI.getText().isEmpty()){
                try{
                    long d = Long.parseLong(v_referenca.getText());
                    n_referenca.setText("");
                } catch (Exception e){
                    n_referenca.setText("!");
                }
            } else{
                n_referenca.setText("!");
            }
        } else if(evt.getSource() == v_postnast){
            try{
                long d = Long.parseLong(v_postnast.getText());
                n_posta.setText("");
            } catch (Exception e){
                n_posta.setText("!");
            }
        }
    }//GEN-LAST:event_UPNnapake

    private void IstaPosNapake(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IstaPosNapake
        if(evt.getSource() == v_strac){
            if(v_strac.getText().isEmpty()){
                n_strac.setText("!");
            } else{
                if(v_strac.getText().equalsIgnoreCase(osebe[1].vrniRacune()[0].vrniStevilko())){
                    v_imeprej.setText(osebe[1].dobiIme());
                }
                n_strac.setText("");
            }
        } else if(evt.getSource() == v_ip_znesek){
            if(v_ip_znesek.getText().isEmpty()){
                n_ip_znesek.setText("!");
            } else{
                try {
                    double d = Double.parseDouble(v_ip_znesek.getText());
                    n_ip_znesek.setText("");
                } catch (Exception e) {
                    n_ip_znesek.setText("!");
                }
            }
        }
    }//GEN-LAST:event_IstaPosNapake

    private void NarediIstaPos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NarediIstaPos
        if(istaPosPreveriVse()){
             try {
                PrintWriter out = new PrintWriter(new FileWriter("istapos"));
                out.println("Podatki o prejemniku:");
                out.println("Ime: " + v_imeprej.getText());
                out.println("Številka računa:");
                out.println(v_strac.getText());         
                out.println("Znesek:");                
                out.println(v_ip_znesek.getText() + " EUR");
                out.println("Hitro plačilo: " + v_hitroplac.getText());
                out.close();
                Obvestilnik.setVisible(true);
                obvestilnik1.setText("Datoteka z imenom istapos.");
                obvestilnik2.setText("Je bila uspešno shranjena.");
            } catch (Exception e) {
                System.err.print(e);
                Obvestilnik.setVisible(true);
                obvestilnik1.setText("Napaka pri pisanju datoteke.");
                obvestilnik2.setText("");
            }
            double d = Double.parseDouble(v_ip_znesek.getText());
            osebe[0].vrniRacune()[0].spremeniStanje(d);
            if(operacije == null){
                operacije = ("nakazilo na račun znotraj banke (»" + v_hitroplac.getText() + "«)\n");
            } else{
                operacije += ("nakazilo na račun znotraj banke (»" + v_hitroplac.getText() + "«)\n");
            }
        } else{
            obvestilnik1.setText("V nekaterih poljih ni pravilnega vnosa.");
            obvestilnik2.setText("Poištite polja označena z !.");
            Obvestilnik.setVisible(true);
        }
    }//GEN-LAST:event_NarediIstaPos

    private void izpisiStanje(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_izpisiStanje
        for(int i = 0; i<osebe[0].vrniRacune().length; i++){
            stanja.setText(stanja.getText() + osebe[0].vrniRacune()[i].vrniVrsto() + ": " + osebe[0].vrniRacune()[i].vrniStanje() + "\n");
        }
        if(operacije == null){
            operacije = "pregled stanja\n";
        } else{
            operacije += "pregled stanja\n";
        }
    }//GEN-LAST:event_izpisiStanje

    private void metodaMeni(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodaMeni
        if(evt.getSource() == m_avtor){
            obvestilnik1.setText("Avtor: Adrian Jarc");
            obvestilnik2.setText("Vpisna številka: 63120165");
            Obvestilnik.setVisible(true);
        } else if(evt.getSource() == m_izhod){
            izpis_operacij.setText(operacije);
            Operacije.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_metodaMeni

    private void Operacije(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Operacije
        izpis_operacij.setText(operacije);
        Operacije.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Operacije

    private boolean preveriPrijavo(String met){
        boolean b = true;
        if (met.equals("prijavi")){
            if(!ime.getText().equalsIgnoreCase(osebe[0].dobiIme())){
                n_ime.setText("!");
                b = false;
            }
            if(!geslo.getText().equals(osebe[0].dobiGeslo())){
                n_geslo.setText("!");
                b = false;
            }
        }else if(met.equals("prijava")){
            if(!ime.getText().equalsIgnoreCase(osebe[0].dobiIme())){
                b = false;
            }
            if(!geslo.getText().equals(osebe[0].dobiGeslo())){
                b = false;
            }
        }
        return b;
    }
    
    private boolean UPNpreveriVse(){
        boolean b = true;
        if(v_IBAN.getText().isEmpty()){
            n_IBAN.setText("!");
            b = false;
        }
        if(v_SI.getText().isEmpty()){
            n_referenca.setText("!");
            b = false;
        }
        if(v_naziv.getText().isEmpty()){
            b = false;
        }
        if(v_posta.getText().isEmpty()){
            n_posta.setText("!");
            b = false;
        }
        if(v_postnast.getText().isEmpty()){
            n_posta.setText("!");
            b = false;
        }
        if(v_referenca.getText().isEmpty()){
            n_referenca.setText("!");
            b = false;
        }
        if(v_ulica.getText().isEmpty()){
            n_posta.setText("!");
            b = false;
        }
        if(v_znesek.getText().isEmpty()){
            n_znesek.setText("!");
            b = false;
        }
        try{
            long d = Long.parseLong(v_referenca.getText());
            n_referenca.setText("");
        } catch (Exception e){
            n_referenca.setText("!");
            b = false;
        }
        try{
            long d = Long.parseLong(v_IBAN.getText());
            n_IBAN.setText("");
        } catch (Exception e){
            n_IBAN.setText("!");
            b = false;
        }
        try{
            double d = Double.parseDouble(v_znesek.getText());
            n_znesek.setText("");
        } catch (Exception e){
            n_znesek.setText("!");
            b = false;
        }
        return b;
    }
    
    private boolean istaPosPreveriVse(){
        boolean b = true;
        if(v_strac.getText().isEmpty()){
            n_strac.setText("!");
            b = false;
        }
        if (v_ip_znesek.getText().isEmpty()){
            n_ip_znesek.setText("!");
            b = false;
        }
        try {
            double d = Double.parseDouble(v_ip_znesek.getText());
            n_ip_znesek.setText("");
        } catch (Exception e) {
            n_ip_znesek.setText("!");
            b = false;
        }
        return b;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banka().setVisible(true);
                osebe[0] = new Oseba("Janko", "Metek", "1337h4x0r", 3);
                osebe[1] = new Oseba("Jurček", "Metek", "abcdefgh", 1);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Datoteka;
    private javax.swing.JScrollPane Izpisi_operacije;
    private javax.swing.JMenuBar Meni;
    private javax.swing.JPanel Nakazilo;
    private javax.swing.JFrame Obvestilnik;
    private javax.swing.JFrame Operacije;
    private javax.swing.JMenu Pomoc;
    private javax.swing.JFrame Prijavnik;
    private javax.swing.JPanel Stanje;
    private javax.swing.JTabbedPane Storitve;
    private javax.swing.JPanel UPN;
    private javax.swing.JPasswordField geslo;
    private javax.swing.JTextField ime;
    private javax.swing.JButton ip_vredu;
    private javax.swing.JTextArea izpis_operacij;
    private javax.swing.JLabel l_EUR;
    private javax.swing.JLabel l_IBAN;
    private javax.swing.JLabel l_SI;
    private javax.swing.JLabel l_SI56;
    private javax.swing.JLabel l_geslo;
    private javax.swing.JLabel l_hitroplac;
    private javax.swing.JLabel l_ime;
    private javax.swing.JLabel l_imeprej;
    private javax.swing.JLabel l_ip_EUR;
    private javax.swing.JLabel l_ip_znesek;
    private javax.swing.JLabel l_naziv;
    private javax.swing.JLabel l_osebnizaz;
    private javax.swing.JLabel l_posta;
    private javax.swing.JLabel l_postnast;
    private javax.swing.JLabel l_referenca;
    private javax.swing.JLabel l_strac;
    private javax.swing.JLabel l_ulica;
    private javax.swing.JLabel l_znesek;
    private javax.swing.JMenuItem m_avtor;
    private javax.swing.JMenuItem m_izhod;
    private javax.swing.JLabel n_IBAN;
    private javax.swing.JLabel n_geslo;
    private javax.swing.JLabel n_ime;
    private javax.swing.JLabel n_ip_znesek;
    private javax.swing.JLabel n_posta;
    private javax.swing.JLabel n_referenca;
    private javax.swing.JLabel n_strac;
    private javax.swing.JLabel n_znesek;
    private javax.swing.JLabel obvestilnik1;
    private javax.swing.JLabel obvestilnik2;
    private javax.swing.JButton obvestilnik_vredu;
    private javax.swing.JButton potrditev;
    private javax.swing.JScrollPane prikaz_stanja;
    private javax.swing.JTextArea stanja;
    private javax.swing.JTextField v_IBAN;
    private javax.swing.JTextField v_SI;
    private javax.swing.JTextField v_hitroplac;
    private javax.swing.JTextField v_imeprej;
    private javax.swing.JTextField v_ip_znesek;
    private javax.swing.JTextField v_naziv;
    private javax.swing.JTextField v_osebnizaz;
    private javax.swing.JTextField v_posta;
    private javax.swing.JTextField v_postnast;
    private javax.swing.JTextField v_referenca;
    private javax.swing.JTextField v_strac;
    private javax.swing.JTextField v_ulica;
    private javax.swing.JTextField v_znesek;
    private javax.swing.JButton vredu;
    // End of variables declaration//GEN-END:variables
}
