/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VB.java
 *
 * Created on Mar 18, 2013, 3:23:31 PM
 */
package fri.kcr;

import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author test
 */
public class VB extends javax.swing.JFrame {

    /** Creates new form VB */
    public VB() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        FileInfo = new javax.swing.JLabel();
        SearchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextContent = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        MenuOpen = new javax.swing.JMenuItem();
        MenuSave = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        MenuFind = new javax.swing.JMenuItem();
        MenuColour = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FileInfo.setText("Status:");
        getContentPane().add(FileInfo, java.awt.BorderLayout.PAGE_END);

        SearchField.setText("Išči...");
        getContentPane().add(SearchField, java.awt.BorderLayout.PAGE_START);

        TextContent.setPreferredSize(new java.awt.Dimension(400, 400));
        jScrollPane1.setViewportView(TextContent);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        File.setText("Datoteka");

        MenuOpen.setText("Odpri");
        MenuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenHandler(evt);
            }
        });
        File.add(MenuOpen);

        MenuSave.setText("Shrani kot...");
        MenuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveHandler(evt);
            }
        });
        File.add(MenuSave);

        MenuExit.setText("Izhod");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitHandler(evt);
            }
        });
        File.add(MenuExit);

        jMenuBar1.add(File);

        Edit.setText("Uredi");

        MenuFind.setText("Najdi");
        MenuFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindHandler(evt);
            }
        });
        Edit.add(MenuFind);

        MenuColour.setText("Spremeni barvo");
        MenuColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColourHandler(evt);
            }
        });
        Edit.add(MenuColour);

        jMenuBar1.add(Edit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void ExitHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitHandler
    System.exit(0);
}//GEN-LAST:event_ExitHandler

private void OpenHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenHandler
    JFileChooser jfc= new JFileChooser();
    if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
        File f = jfc.getSelectedFile();
        FileInfo.setText(f.getName());
        try{
            TextContent.read(new FileReader(f),null);
        }catch(Exception e){
            FileInfo.setText("Napaka pri branju datoteke.");
            System.err.println(e.getMessage());                 //izhod za napake
        }
    }
}//GEN-LAST:event_OpenHandler

private void SaveHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveHandler
    if(jFileChooser1.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
        File f=jFileChooser1.getSelectedFile();
        FileInfo.setText(f.getName());
        try{
            TextContent.write(new FileWriter(f));
        }catch(Exception e){
            FileInfo.setText("Napaka pri pisanju datoteke.");
            System.err.println(e.getMessage());
        }
    }
}//GEN-LAST:event_SaveHandler

private void ColourHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColourHandler
    Color c = JColorChooser.showDialog(this, "Izberi barvo...", Color.BLUE);
    if(c == null) return;
    StyledDocument sd = TextContent.getStyledDocument();
    Style s = TextContent.addStyle("TextForeground", null);    
    StyleConstants.setForeground(s, c);
    sd.setCharacterAttributes(0, TextContent.getText().length(), s, false);
}//GEN-LAST:event_ColourHandler

private void FindHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindHandler
    String searchString = SearchField.getText();
    String replaceString = "_XXXXXXXXXXXXXX_";
    int i = TextContent.getText().indexOf(searchString, 0);
    if(i<0) return;
    TextContent.select(i, i + searchString.length());
    TextContent.replaceSelection(replaceString);
    TextContent.grabFocus();
    TextContent.moveCaretPosition(i);
}//GEN-LAST:event_FindHandler

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VB().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu File;
    private javax.swing.JLabel FileInfo;
    private javax.swing.JMenuItem MenuColour;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenuItem MenuFind;
    private javax.swing.JMenuItem MenuOpen;
    private javax.swing.JMenuItem MenuSave;
    private javax.swing.JTextField SearchField;
    private javax.swing.JTextPane TextContent;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
